import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar/page";
import Footer from "./footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Como Laundry",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full overflow-y-scroll scrollbar-hide">
          {/* <Navbar className="fixed top-0 left-0 right-0 z-50 shadow-md" /> */}
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
