version: '3'
services:
  nextjs:
    build: .
    container_name: nextjs
    ports:
      - "3000:3000"
  
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nextjs