version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    networks:
      - como-network

networks:
  como-network: {}
