import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";
import Footer from "./footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Como Laundry",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section className="w-full scrollbar-hide">
          <Navbar className="sticky top-0" />
          {children}
          <Footer />
        </section>
      </body>
    </html>
  );
}
